export const CONSOLE_FAMILIES = [
  ["xbox_series_x", ["xbox series x", "series x"]],
  ["xbox_series_s", ["xbox series s", "series s"]],
  ["switch_oled", ["switch oled", "nintendo switch oled", "oled model"]],
  ["switch_lite", ["switch lite", "nintendo switch lite"]],
  ["switch_v2", ["nintendo switch", "switch console"]],
];

export const CONSOLE_CATEGORY_TERMS = [
  "video game consoles",
  "consoles",
  "home consoles",
  "game consoles",
];

export const ACCESSORY_CATEGORY_TERMS = [
  "controllers attachments",
  "controllers and attachments",
  "video game accessories",
  "accessories",
  "headsets",
  "chargers docks",
  "chargers and docks",
  "replacement parts tools",
  "replacement parts and tools",
  "bags skins travel",
  "bags skins and travel",
];

export const NON_CONSOLE_CATEGORY_TERMS = [
  "video game merchandise",
  "merchandise",
  "video games",
  "strategy guides cheats",
  "strategy guides & cheats",
  "soundtracks",
  "books, comics & magazines",
  "action figures",
  "toys to life products",
];

export const HARD_NON_CONSOLE_CATEGORY_TERMS = [
  "art",
  "art drawings",
  "drawings",
  "paintings",
  "prints",
  "posters",
  "canvas",
  "collectibles",
  "collectable card games",
  "trading card games",
  "coins",
  "stamps",
  "pottery",
  "ceramics",
  "antiques",
  "jewellery",
  "jewelry",
  "clothes shoes accessories",
  "fashion",
  "books",
  "magazines",
  "music",
  "records",
  "vinyl",
  "dolls bears",
  "toys",
  "model railways",
  "cameras photography",
  "mobile phones communication",
  "computers tablets networking",
  "home furniture diy",
  "health beauty",
  "sporting goods",
  "vehicle parts accessories",
  "pet supplies",
  "crafts",
];

export const ACCESSORY_TERMS = [
  "controller only",
  "dualsense only",
  "dualshock only",
  "joy con only",
  "joy-con only",
  "remote only",
  "headset only",
  "charger only",
  "charging dock",
  "charging stand",
  "dock only",
  "dock station",
  "vertical stand",
  "base stand",
  "stand only",
  "faceplate",
  "face plate",
  "shell only",
  "replacement shell",
  "replacement housing",
  "cover only",
  "skin only",
  "case only",
  "carry case",
  "thumb grips",
  "thumb grip",
  "media remote",
  "remote control",
  "headset",
  "charger",
  "power cable only",
  "cable only",
  "hdmi cable",
  "fan only",
  "cooling fan",
  "mount only",
  "disc drive only",
  "disc drive",
  "disk drive",
  "disc reader only",
  "disk reader only",
  "replacement disc drive",
  "replacement disk drive",
  "external disc drive",
  "external disk drive",
  "slim disc drive",
  "slim disk drive",
  "replacement part",
  "replacement parts",
  "portal",
  "playstation portal",
  "psvr",
  "vr2",
  "playstation vr",
  "empty box",
  "box only",
  "manual only",
  "cover plate",
  "side plate",
  "charger dock",
  "cooler",
  "cooling stand",
  "shell cover",
  "console shell",
  "replacement fan",
  "housing only",
  "outer shell",
  "storage expansion card",
  "expansion card only",
  "ssd only",
  "internal ssd",
  "nvme",
  "memory card",
];

export const NON_CONSOLE_TERMS = [
  "collector’s edition",
  "collector's edition",
  "collectors edition",
  "collector edition",
  "game not included",
  "no game",
  "without game",
  "disc only",
  "game only",
  "ps5 game",
  "playstation 5 game",
  "steelbook",
  "steel book",
  "art book",
  "artbook",
  "soundtrack",
  "figurine",
  "figure",
  "statue",
  "merchandise",
  "merch",
  "poster",
  "novelty",
  "keyring",
  "keychain",
  "mouse mat",
  "mousepad",
  "t shirt",
  "t-shirt",
  "hoodie",
  "lamp",
  "display stand",
  "display piece",
  "ornament",
  "vinyl",
  "sound track",
  "dlc",
  "download code",
  "digital code",
  "voucher",
  "gift card",
  "season pass",
  "wall art",
  "canvas print",
  "membership",
  "subscription",
  "nintendo switch online",
  "online expansion pack",
  "expansion pack",
  "online membership",
  "membership code",
  "digital download",
  "digital item",
  "digital only",
  "emailed code",
  "email delivery",
  "instant delivery",
  "account",
  "accounts",
];

export const HARD_REJECT_TERMS = [
  "for parts",
  "for spares",
  "spares or repairs",
  "spares repairs",
  "parts only",
  "faulty",
  "broken",
  "not working",
  "no power",
  "wont turn on",
  "won't turn on",
  "will not turn on",
  "repair required",
  "needs repair",
  "water damaged",
  "motherboard fault",
  "blue light of death",
  "console banned",
  "banned",
  "account locked",
  "motherboard only",
  "shell only",
  "empty box",
  "box only",
  "bricked",
  "dead console",
];

export const PS5_GAME_TERMS = [
  "fifa",
  "fc 24",
  "fc24",
  "fc 25",
  "fc25",
  "cod",
  "call of duty",
  "spiderman",
  "spider man",
  "spider-man",
  "gow",
  "god of war",
  "gran turismo",
  "gt7",
  "gta",
  "horizon",
  "last of us",
  "minecraft",
  "elden ring",
  "ratchet",
  "returnal",
  "ea sports fc",
  "astro bot",
];

export const XBOX_GAME_TERMS = [
  "battlefield",
  "call of duty",
  "cod",
  "fifa",
  "fc 24",
  "fc24",
  "fc 25",
  "fc25",
  "forza",
  "halo",
  "gears",
  "gears of war",
  "starfield",
  "minecraft",
  "mindseye",
  "dying light",
  "grand theft auto",
  "gta",
  "tt isle of man",
  "ride on the edge",
  "everspace",
  "like a dragon",
  "ishin",
  "stellar edition",
  "adventure",
  "shoot em up",
  "shoot 'em up",
  "pegi",
];

export const XBOX_CONSOLE_INTENT_TERMS = [
  "console",
  "1tb",
  "2tb",
  "512gb",
  "standard edition",
  "boxed",
  "box included",
  "original box",
  "complete in box",
  "no box",
  "unboxed",
  "with controller",
  "controller included",
  "includes controller",
  "bundle",
  "system",
  "home console",
  "video console",
  "carbon black",
  "galaxy black",
  "console only",
  "no controller",
  "without controller",
  "controller not included",
  "pad included",
  "pad not included",
];

export const SWITCH_CONSOLE_INTENT_TERMS = [
  "console",
  "tablet",
  "32gb",
  "64gb",
  "boxed",
  "box included",
  "original box",
  "complete in box",
  "no box",
  "unboxed",
  "with joy cons",
  "with joy-con",
  "with joy-cons",
  "joy cons included",
  "joy-con included",
  "joy-cons included",
  "dock included",
  "with dock",
  "official dock",
  "charger included",
  "bundle",
  "system",
  "oled model",
  "switch oled",
  "switch lite",
  "nintendo switch console",
  "switch console",
  "hac-001",
  "hac 001",
  "hac-001(-01)",
  "hac 001(-01)",
  "hadh-001",
  "hadh 001",
  "hdh-001",
  "hdh 001",
];

export const SWITCH_GAME_TERMS = [
  "mario kart",
  "mario wonder",
  "zelda",
  "pokemon",
  "animal crossing",
  "splatoon",
  "metroid",
  "kirby",
  "smash bros",
  "super smash",
  "luigis mansion",
  "luigi's mansion",
  "minecraft",
  "fifa",
  "fc 24",
  "fc24",
  "fc 25",
  "fc25",
  "pegi",
  "game card",
  "cartridge",
  "download code",
];

export const SWITCH_PARTS_TERMS = [
  "replacement battery",
  "battery replacement",
  "battery for nintendo switch",
  "battery for switch",
  "hac-003",
  "hac 003",
  "replacement part",
  "replacement parts",
  "spare part",
  "spare parts",
  "repair part",
  "repair parts",
  "joy con rail",
  "joy-con rail",
  "rail replacement",
  "game card reader",
  "card reader replacement",
  "usb c port",
  "usb-c port",
  "charge port",
  "charging port",
  "lcd replacement",
  "digitizer",
  "touch screen replacement",
  "screen replacement",
  "replacement screen",
  "replacement lcd",
  "motherboard",
  "daughterboard",
  "speaker replacement",
  "fan replacement",
  "replacement fan",
  "housing replacement",
  "shell replacement",
];

export const PS5_DISC_CUSTOM_STORAGE_TERMS = [
  "upgraded ssd",
  "ssd upgrade",
  "storage upgrade",
  "upgraded storage",
  "expanded storage",
  "storage expanded",
  "extra ssd",
  "additional ssd",
  "added ssd",
  "ssd added",
  "internal ssd",
  "internal nvme",
  "nvme installed",
  "with ssd",
  "with 1tb ssd",
  "with 2tb ssd",
  "custom storage",
  "custom upgraded storage",
  "expanded nvme",
  "m2 ssd",
  "m.2 ssd",
  "sn850",
  "sn850x",
  "990 pro",
  "980 pro",
  "firecuda",
  "wd black",
  "seagate",
];

export const MINOR_WARNING_TERMS = [
  ["read description", "Read description carefully"],
  ["read desc", "Read description carefully"],
  ["see description", "Read description carefully"],
  ["read caption", "Seller may have important notes in caption"],
  ["see caption", "Seller may have important notes in caption"],
  ["no returns", "No returns accepted"],
  ["untested", "Untested listing"],
  ["poor condition", "Condition may reduce resale appeal"],
  ["heavy wear", "Condition may reduce resale appeal"],
  ["heavily used", "Condition may reduce resale appeal"],
  ["lot of wear", "Condition may reduce resale appeal"],
  ["bad condition", "Condition may reduce resale appeal"],
  ["fair condition", "Condition may reduce resale appeal"],
  ["well used", "Condition may reduce resale appeal"],
  ["worn", "Condition may reduce resale appeal"],
  ["scratches", "Visible cosmetic wear mentioned"],
  ["scratched", "Visible cosmetic wear mentioned"],
  ["scratch", "Visible cosmetic wear mentioned"],
  ["scratched up", "Visible cosmetic wear mentioned"],
  ["heavy scratches", "Visible cosmetic wear mentioned"],
  ["wear scratch", "Visible cosmetic wear mentioned"],
  ["cosmetic marks", "Condition may reduce resale appeal"],
  ["cosmetic wear", "Condition may reduce resale appeal"],
  ["missing controller", "No controller included"],
  ["no controller", "No controller included"],
  ["without controller", "No controller included"],
  ["console only", "Console-only listing"],
  ["unit only", "Console-only listing"],
  ["tablet only", "Console-only listing"],
  ["unboxed", "No box included"],
  ["no box", "No box included"],
  ["without box", "No box included"],
  ["low firmware", "Specialist buyer wording"],
  ["jailbreak", "Specialist buyer wording"],
  ["modded", "Specialist buyer wording"],
  ["modded firmware", "Specialist buyer wording"],
  ["doesnt read discs", "Disc drive issue mentioned"],
  ["doesn't read discs", "Disc drive issue mentioned"],
  ["wont read discs", "Disc drive issue mentioned"],
  ["won't read discs", "Disc drive issue mentioned"],
  ["hdmi issue", "HDMI issue mentioned"],
  ["hdmi fault", "HDMI issue mentioned"],
  ["overheating", "Overheating risk mentioned"],
  ["game error", "Error wording mentioned"],
  ["system error", "Error wording mentioned"],
  ["error code", "Error wording mentioned"],
  ["console error", "Error wording mentioned"],
  ["software issue", "Issue wording mentioned"],
  ["system issue", "Issue wording mentioned"],
  ["console issue", "Issue wording mentioned"],
  ["freezing", "Stability issue mentioned"],
  ["freezes", "Stability issue mentioned"],
  ["crashing", "Stability issue mentioned"],
  ["crashes", "Stability issue mentioned"],
  ["glitching", "Stability issue mentioned"],
  ["glitches", "Stability issue mentioned"],
  ["stuck on", "Boot or loading issue mentioned"],
  ["safe mode", "Boot or loading issue mentioned"],
  ["wont load", "Boot or loading issue mentioned"],
  ["won't load", "Boot or loading issue mentioned"],
  ["not loading", "Boot or loading issue mentioned"],
  ["load issue", "Boot or loading issue mentioned"],
];

export const CONSOLE_ONLY_QUERY_TERMS = [
  "console only",
  "unit only",
  "main unit only",
  "base unit only",
  "body only",
  "just console",
  "without controller",
  "missing controller",
  "no controller",
  "controller not included",
  "pad not included",
];

export const FAULTY_OR_PARTS_EXTRA_TERMS = [
  "game error",
  "system error",
  "console error",
  "error code",
  "safe mode loop",
  "stuck in safe mode",
  "stuck on safe mode",
  "stuck on logo",
  "stuck on startup",
  "stuck on start up",
  "stuck on boot",
  "boot loop",
  "bootloop",
  "freezing",
  "freezes",
  "keeps freezing",
  "crashing",
  "crashes",
  "keeps crashing",
  "glitching",
  "glitches",
  "software issue",
  "system issue",
  "console issue",
  "gpu issue",
  "power issue",
  "overheats",
  "over heating",
  "wont load",
  "won't load",
  "not loading",
  "load issue",
  "corrupted",
  "corrupt data",
];

export const PS5_BUNDLE_DEBUG_KEYS = [
  "ps5BundleCandidateTrue",
  "ps5BundleCandidateFalse",
  "hardPs5Reject",
  "hardPs5Accessory",
  "hardNonConsoleCategory",
  "failsSharedConsoleGate",
  "clearlyNonConsole",
  "hardAccessoryListing",
  "consoleTypeDigitalMismatch",
  "storageMismatch",
  "passed",
];
